import esbuild from "esbuild";
import console from "node:console";
import { builtinModules } from "node:module";
import process from "node:process";
import { z } from "zod";

// Load environment variables from .env (if present)
try {
  process.loadEnvFile();
} catch {
  // .env file doesn't exist — that's fine, env vars are set externally in CI
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((module_) => `node:${module_}`),
];

const baseOptions = {
  entryPoints: ["src/plugin/index.ts"],
  bundle: true,
  format: "cjs",
  target: "es2021",
  outfile: "main.js",
  banner: { js: banner },
  external: externalDependencies,
  logLevel: "info",
  treeShaking: true,
};

const environmentSchema = z.object({
  GOOGLE_CLIENT_ID: z.string().min(1, "GOOGLE_CLIENT_ID is required"),
});

/**
 * Validates and returns the Google Client ID for the current build mode.
 * Production builds require GOOGLE_CLIENT_ID_PROD.
 * Development builds require GOOGLE_CLIENT_ID_DEV.
 */
const getValidatedClientId = (mode) => {
  const environmentVariableName =
    mode === "production" ? "GOOGLE_CLIENT_ID_PROD" : "GOOGLE_CLIENT_ID_DEV";
  const clientId = process.env[environmentVariableName];

  if (!clientId || clientId.trim() === "") {
    throw new Error(
      `Google Client ID is required. Set ${environmentVariableName} environment variable.`,
    );
  }

  const result = environmentSchema.safeParse({ GOOGLE_CLIENT_ID: clientId });
  if (!result.success) {
    const issues = result.error.issues
      .map((issue) => `${issue.path.join(".")}: ${issue.message}`)
      .join("; ");
    throw new Error(`Invalid Google Client ID: ${issues}`);
  }

  return result.data.GOOGLE_CLIENT_ID;
};

/**
 * Creates production build options with the validated client ID.
 */
const createProductionOptions = (clientId) => ({
  ...baseOptions,
  sourcemap: false,
  minify: true,
  define: {
    "process.env": JSON.stringify({
      GOOGLE_CLIENT_ID: clientId,
    }),
  },
});

/**
 * Creates development build options with the validated client ID.
 */
const createDevelopmentOptions = (clientId) => ({
  ...baseOptions,
  sourcemap: "inline",
  minify: false,
  define: {
    "process.env": JSON.stringify({
      GOOGLE_CLIENT_ID: clientId,
    }),
  },
});

/**
 * Builds the plugin using esbuild with the provided options.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const build = async (options) => {
  console.info("🔧 Building...");
  const context = await esbuild.context(options);
  try {
    await context.rebuild();
    console.info("✅ Build succeeded.");
  } finally {
    await context.dispose();
  }
};

/**
 * Starts a file watcher that rebuilds the plugin on file changes.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const watch = async (options) => {
  console.info("👀 Watching for changes...");
  const context = await esbuild.context(options);

  context.watch().catch((error) => {
    console.error("❌ Watch failed:", error);
  });
};

/**
 * Parses the build mode from command-line arguments.
 *
 * @returns {"production" | "development" | "watch"} The current mode.
 */
const getMode = () => {
  const modeFlagIndex = process.argv.indexOf("--mode");
  return modeFlagIndex !== -1 && modeFlagIndex + 1 < process.argv.length
    ? process.argv[modeFlagIndex + 1]
    : "watch"; // default is "watch"
};

/**
 * Main entry point. Executes the appropriate build or watch based on the mode.
 *
 * @returns {Promise<void>}
 */
const run = async () => {
  const mode = getMode();
  console.info(`🚀 Starting build script in mode: ${mode}`);

  // Get and validate the appropriate client ID for this build mode
  const clientId = getValidatedClientId(mode);
  const clientIdType = mode === "production" ? "PROD" : "DEV";
  console.info(`🔑 Using Google Client ID (${clientIdType}): ${clientId.slice(0, 20)}...`);

  switch (mode) {
    case "production": {
      const options = createProductionOptions(clientId);
      await build(options);
      break;
    }
    case "development": {
      const options = createDevelopmentOptions(clientId);
      await build(options);
      break;
    }
    default: {
      const options = createDevelopmentOptions(clientId);
      await watch(options);
    }
  }
};

await run();
