import esbuild from "esbuild";
import console from "node:console";
import path from "node:path";
import { copyFileSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { z } from "zod";

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const sqlWasmSourcePath = path.join(currentDirectory, "node_modules/sql.js/dist/sql-wasm.wasm");

/**
 * Copies sql.js WASM next to main.js so the plugin can load it without a remote fetch.
 */
const copySqlWasmPlugin = {
  name: "copy-sql-wasm",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) {
        return;
      }
      const outputDirectory = path.dirname(baseOptions.outfile);
      copyFileSync(sqlWasmSourcePath, path.join(outputDirectory, "sql-wasm.wasm"));
      console.info("Copied sql-wasm.wasm to plugin output directory.");
    });
  },
};

// Load environment variables from .env (if present)
try {
  process.loadEnvFile();
} catch {
  // .env file doesn't exist — that's fine, env vars are set externally in CI
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((module_) => `node:${module_}`),
];

const baseOptions = {
  entryPoints: ["src/plugin/index.ts"],
  bundle: true,
  format: "cjs",
  target: "es2021",
  outfile: "main.js",
  banner: { js: banner },
  external: externalDependencies,
  plugins: [copySqlWasmPlugin],
  logLevel: "info",
  treeShaking: true,
};

const environmentSchema = z.object({
  GOOGLE_TASKS_CLIENT_ID: z.string().min(1, "GOOGLE_TASKS_CLIENT_ID is required"),
});

/**
 * Returns the Outlook client ID for the current build mode.
 * Production builds require OUTLOOK_CLIENT_ID_PROD (Outlook is a shipped feature).
 * Development builds treat OUTLOOK_CLIENT_ID_DEV as optional (Outlook Connect disabled if omitted).
 */
const getOutlookClientId = (mode) => {
  const environmentVariableName =
    mode === "production" ? "OUTLOOK_CLIENT_ID_PROD" : "OUTLOOK_CLIENT_ID_DEV";
  const clientId = process.env[environmentVariableName];
  const trimmed = typeof clientId === "string" ? clientId.trim() : "";

  if (mode === "production" && trimmed.length === 0) {
    throw new Error(
      `Outlook Client ID is required for production builds. Set ${environmentVariableName} environment variable.`,
    );
  }

  return trimmed;
};

/**
 * Validates and returns the Google Tasks client ID for the current build mode.
 * Production builds require GOOGLE_TASKS_CLIENT_ID_PROD.
 * Development builds require GOOGLE_TASKS_CLIENT_ID_DEV.
 */
const getValidatedClientId = (mode) => {
  const environmentVariableName =
    mode === "production" ? "GOOGLE_TASKS_CLIENT_ID_PROD" : "GOOGLE_TASKS_CLIENT_ID_DEV";
  const clientId = process.env[environmentVariableName];

  if (!clientId || clientId.trim() === "") {
    throw new Error(
      `Google Tasks client ID is required. Set ${environmentVariableName} environment variable.`,
    );
  }

  const result = environmentSchema.safeParse({ GOOGLE_TASKS_CLIENT_ID: clientId });
  if (!result.success) {
    const issues = result.error.issues
      .map((issue) => `${issue.path.join(".")}: ${issue.message}`)
      .join("; ");
    throw new Error(`Invalid Google Tasks client ID: ${issues}`);
  }

  return result.data.GOOGLE_TASKS_CLIENT_ID;
};

/**
 * Creates production build options with the validated client ID.
 *
 * @param {string} clientId
 * @param {string} outlookClientId
 */
const createProductionOptions = (clientId, outlookClientId) => ({
  ...baseOptions,
  sourcemap: false,
  minify: true,
  define: {
    "process.env": JSON.stringify({
      GOOGLE_TASKS_CLIENT_ID: clientId,
      OUTLOOK_CLIENT_ID: outlookClientId,
    }),
  },
});

/**
 * Creates development build options with the validated client ID.
 *
 * @param {string} clientId
 * @param {string} outlookClientId
 */
const createDevelopmentOptions = (clientId, outlookClientId) => ({
  ...baseOptions,
  sourcemap: "inline",
  minify: false,
  define: {
    "process.env": JSON.stringify({
      GOOGLE_TASKS_CLIENT_ID: clientId,
      OUTLOOK_CLIENT_ID: outlookClientId,
    }),
  },
});

/**
 * Builds the plugin using esbuild with the provided options.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const build = async (options) => {
  console.info("Building...");
  const context = await esbuild.context(options);
  try {
    await context.rebuild();
    console.info("Build succeeded.");
  } finally {
    await context.dispose();
  }
};

/**
 * Starts a file watcher that rebuilds the plugin on file changes.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const watch = async (options) => {
  console.info("Watching for changes...");
  const context = await esbuild.context(options);

  context.watch().catch((error) => {
    console.error("Watch failed:", error);
  });
};

/**
 * Parses and normalises the build mode from command-line arguments.
 *
 * @returns {"production" | "development" | "watch"} The current mode.
 */
const getMode = () => {
  const modeFlagIndex = process.argv.indexOf("--mode");
  if (modeFlagIndex === -1) {
    return "watch";
  }

  const rawMode = process.argv[modeFlagIndex + 1];

  switch (rawMode) {
    case "prod":
    case "production": {
      return "production";
    }
    case "dev":
    case "development": {
      return "development";
    }
    case "watch": {
      return "watch";
    }
    default: {
      throw new Error(
        `Unknown build mode "${String(rawMode)}". Use one of: dev, prod, development, production, watch.`,
      );
    }
  }
};

/**
 * Main entry point. Executes the appropriate build or watch based on the mode.
 *
 * @returns {Promise<void>}
 */
const run = async () => {
  const mode = getMode();
  console.info(`Starting build script in mode: ${mode}`);

  // Get and validate the appropriate client ID for this build mode
  const clientId = getValidatedClientId(mode);
  const clientIdType = mode === "production" ? "PROD" : "DEV";
  console.info(`Using Google Tasks Client ID (${clientIdType}): ${clientId.slice(0, 20)}...`);

  const outlookClientId = getOutlookClientId(mode === "production" ? "production" : "development");
  if (outlookClientId.length > 0) {
    console.info(`Using Outlook Client ID (${clientIdType}): ${outlookClientId.slice(0, 8)}...`);
  } else {
    console.info("Outlook Client ID not set (Outlook connect disabled until configured).");
  }

  switch (mode) {
    case "production": {
      const options = createProductionOptions(clientId, outlookClientId);
      await build(options);
      break;
    }
    case "development": {
      const options = createDevelopmentOptions(clientId, outlookClientId);
      await build(options);
      break;
    }
    default: {
      const options = createDevelopmentOptions(clientId, outlookClientId);
      await watch(options);
    }
  }
};

await run();
