import esbuild from "esbuild";
import console from "node:console";
import { existsSync, readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";
import { z } from "zod";

const rootDirectory = path.dirname(fileURLToPath(import.meta.url));

/** @typedef {"dev" | "staging" | "prod"} BuildEnvironment */

const oauthClientsFileByMode = {
  dev: "oauth-clients.dev.json",
  staging: "oauth-clients.staging.json",
  prod: "oauth-clients.prod.json",
};

// Extra keys must fail the build; default z.object() would strip them.
const oauthClientsSchema = z
  .object({
    GOOGLE_CLIENT_ID: z.string(),
    MICROSOFT_CLIENT_ID: z.string(),
    TODOIST_CLIENT_ID: z.string(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),
  })
  .strict();

/**
 * @typedef {z.infer<typeof oauthClientsSchema>} OAuthClientsConfig
 */

/**
 * Returns the OAuth clients JSON path for a build mode.
 *
 * @param {BuildEnvironment} buildEnvironment
 * @returns {string}
 */
const getOAuthClientsPath = (buildEnvironment) => {
  const fileName = oauthClientsFileByMode[buildEnvironment];
  return path.join(rootDirectory, fileName);
};

/**
 * Reads and validates OAuth client configuration for the given build environment.
 * The file must exist in all environments. Staging and production require
 * non-empty OAuth values.
 *
 * @param {BuildEnvironment} buildEnvironment
 * @returns {OAuthClientsConfig}
 */
const readOAuthClients = (buildEnvironment) => {
  const clientsPath = getOAuthClientsPath(buildEnvironment);

  if (!existsSync(clientsPath)) {
    throw new Error(
      `Missing OAuth clients file: ${oauthClientsFileByMode[buildEnvironment]}. Copy oauth-clients.dev.json.example for dev, or ensure committed staging/prod JSON exists.`,
    );
  }

  const raw = readFileSync(clientsPath, "utf8");
  const parsed = oauthClientsSchema.parse(JSON.parse(raw));

  if (buildEnvironment !== "dev") {
    for (const key of [
      "GOOGLE_CLIENT_ID",
      "GOOGLE_CLIENT_SECRET",
      "MICROSOFT_CLIENT_ID",
      "TODOIST_CLIENT_ID",
    ]) {
      const value = (parsed[key] ?? "").trim();
      if (value.length === 0) {
        throw new Error(`${key} is required in ${oauthClientsFileByMode[buildEnvironment]}.`);
      }
    }
  }

  return parsed;
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const externalDependencies = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
  ...builtinModules.map((module_) => `node:${module_}`),
];

const baseOptions = {
  entryPoints: ["src/plugin/index.ts"],
  bundle: true,
  format: "cjs",
  target: "es2021",
  outfile: "main.js",
  banner: { js: banner },
  external: externalDependencies,
  loader: {
    ".wasm": "binary",
  },
  logLevel: "info",
  treeShaking: true,
};

/**
 * Creates build options with OAuth client IDs injected at build time.
 *
 * @param {OAuthClientsConfig} clients
 * @param {BuildEnvironment} buildEnvironment
 * @param {boolean} watchMode
 */
const createBuildOptions = (clients, buildEnvironment, watchMode) => ({
  ...baseOptions,
  sourcemap: buildEnvironment === "dev" ? "inline" : false,
  minify: buildEnvironment !== "dev",
  define: {
    __ENABLE_GOOGLE__: buildEnvironment === "prod" ? "false" : "true",
    __GOOGLE_CLIENT_ID__: JSON.stringify(clients.GOOGLE_CLIENT_ID.trim()),
    __GOOGLE_CLIENT_SECRET__: JSON.stringify((clients.GOOGLE_CLIENT_SECRET ?? "").trim()),
    __MICROSOFT_CLIENT_ID__: JSON.stringify(clients.MICROSOFT_CLIENT_ID.trim()),
    __TODOIST_CLIENT_ID__: JSON.stringify(clients.TODOIST_CLIENT_ID.trim()),
  },
  ...(watchMode ? { sourcemap: "inline", minify: false } : {}),
});

/**
 * Builds the plugin using esbuild with the provided options.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const build = async (options) => {
  console.info("Building...");
  const context = await esbuild.context(options);
  try {
    await context.rebuild();
    console.info("Build succeeded.");
  } finally {
    await context.dispose();
  }
};

/**
 * Starts a file watcher that rebuilds the plugin on file changes.
 *
 * @param {esbuild.BuildOptions} options - The build options for esbuild.
 * @returns {Promise<void>}
 */
const watch = async (options) => {
  console.info("Watching for changes...");
  const context = await esbuild.context(options);

  context.watch().catch((error) => {
    console.error("Watch failed:", error);
  });
};

/**
 * Parses and normalises build environment from BUILD_ENV.
 *
 * @returns {BuildEnvironment}
 */
const getBuildEnvironment = () => {
  const rawBuildEnvironment = process.env.BUILD_ENV?.trim().toLowerCase();
  if (rawBuildEnvironment === undefined || rawBuildEnvironment.length === 0) {
    throw new Error("Missing BUILD_ENV. Use one of: dev, staging, prod.");
  }

  switch (rawBuildEnvironment) {
    case "dev":
    case "development": {
      return "dev";
    }
    case "staging": {
      return "staging";
    }
    case "prod":
    case "production": {
      return "prod";
    }
    default: {
      throw new Error(
        `Unknown BUILD_ENV "${String(rawBuildEnvironment)}". Use one of: dev, staging, prod.`,
      );
    }
  }
};

/**
 * Logs which OAuth client IDs are active for this build.
 *
 * @param {BuildEnvironment} buildEnvironment
 * @param {OAuthClientsConfig} clients
 */
const logOAuthClients = (buildEnvironment, clients) => {
  for (const [key, value] of [
    ["Google", clients.GOOGLE_CLIENT_ID],
    ["Microsoft", clients.MICROSOFT_CLIENT_ID],
    ["Todoist", clients.TODOIST_CLIENT_ID],
  ]) {
    const trimmed = value.trim();
    if (trimmed.length > 0) {
      console.info(`Using ${key} Client ID (${buildEnvironment}): ${trimmed.slice(0, 20)}...`);
    } else {
      console.info(
        `${key} Client ID not set (${buildEnvironment}; Connect disabled until configured).`,
      );
    }
  }

  console.info(
    `Google integration enabled at build-time: ${buildEnvironment === "prod" ? "no" : "yes"}`,
  );
};

/**
 * Main entry point. Executes the appropriate build or watch based on the mode.
 *
 * @returns {Promise<void>}
 */
const run = async () => {
  const buildEnvironment = getBuildEnvironment();
  const watchMode = process.argv.includes("--watch");
  const runMode = watchMode ? "watch" : "build";
  console.info(`Starting build script in mode: ${runMode} (${buildEnvironment})`);

  const clients = readOAuthClients(buildEnvironment);
  logOAuthClients(buildEnvironment, clients);

  const options = createBuildOptions(clients, buildEnvironment, watchMode);
  if (watchMode) {
    await watch(options);
    return;
  }

  await build(options);
};

await run();
